spring:
    datasource:
        url: jdbc:h2:mem:newdb
    jpa:
        generate-ddl: true
        properties:
            hibernate.globally_quoted_identifiers: true
    h2:
        console:
            enabled: true
    profiles:
        include: oauth,s3
    session:
        store-type: jdbc
    servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 10MB

logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: ERROR